name: tochegando_cliente
description: "Aplicativo cliente do sistema TÃ´ Chegando Delivery."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  meta: ^1.12.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.17
  carousel_slider_plus: ^7.1.0
  pin_code_fields: ^8.0.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  page_transition: ^2.1.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  audioplayers: ^6.4.0
  path_provider: ^2.1.4
  uuid: ^4.5.1
  change_app_package_name: ^1.5.0
  flutter_inappwebview: ^6.0.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.4
  rxdart: ^0.28.0
  file_picker: ^8.0.5
  device_info_plus: ^11.3.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  google_maps_flutter: ^2.12.0
  flutter_map: ^8.1.1
  location: ^8.0.0
  geolocator: ^13.0.3
  latlong2: ^0.9.1
  flutter_local_notifications: ^19.0.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_messaging: ^15.2.4
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  flutter_contacts: ^1.1.9
  connectivity_plus: ^6.1.3
  package_info_plus: ^4.1.0
  vector_math: ^2.1.4
  flutter_animarker: ^3.4.0-beta.1
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  flutter_stripe: ^11.4.0
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/audio/
